services:
  - redis-server
language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - pip install -r requirements.txt
# command to run tests
before_script:
 - mkdir -p media
 - mkdir -p static
 - python manage.py migrate --noinput
 - python manage.py collectstatic --noinput
script:
 - python manage.py test
 - flake8 ozp ozpcenter ozpiwc plugins plugins_util --ignore=E501,E123,E128,E121,E124,E711,E402 --exclude=ozpcenter/scripts/* --show-source


